name = "TheocordMC-S2"
author = "Comet_System & FractalGeodes"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "252e177ab5e536a8121df49d98fd2face0b855dea95ecd64903877ed13e37a3b"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
