name = "TheocordMC-S2"
author = "Comet_System & FractalGeodes"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f48ce5a3d20e61edbd8cf59e5583a684a7a1be8a203c82ed5fc5aa2dbc69a38"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
