name = "TheocordMC-S2"
author = "Comet_System & FractalGeodes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9b5bae5b0ddad82ab864c77f138ea40b5e675265574b7c351aa7c6fb22c68fa"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
